<a href="https://colab.research.google.com/github/anruki/APRENDIZAJE_AUTOMATICO_23_24/blob/main/AlgGen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import math
def binary_matrix_to_decimal_signed(binary_matrix):
    binary_matrix = np.array(binary_matrix)
    num_vectors, vector_length = binary_matrix.shape

    decimal_values = []

    for vector_index in range(num_vectors):
        decimal_value = 0

        # Check if the binary vector is negative (MSB is 1)
        if binary_matrix[vector_index, 0] == 1:
            # Convert the binary vector to its signed decimal equivalent using two's complement
            binary_vector = binary_matrix[vector_index]
            inverted_vector = 1 - binary_vector
            decimal_value = -1 * (int(''.join(map(str, inverted_vector)), 2) + 1)
        else:
            # Convert the positive binary vector to decimal
            for bit_index in range(vector_length):
                decimal_value += binary_matrix[vector_index, bit_index] * (2 ** (vector_length - 1 - bit_index))

        decimal_values.append(decimal_value)

    return decimal_values

def calcular_estadisticas(resultados):
    resultados = np.array(resultados)
    suma_total = np.sum(resultados)
    valor_minimo = np.min(resultados)
    media = np.mean(resultados)

    return suma_total, valor_minimo, media



def f(x_vector):
    x_vector = np.array(x_vector)
    result_vector = 3 * x_vector * np.exp(x_vector)
    return result_vector

def probabilidad(resultados,suma):
    resultados = np.array(resultados)
    prob = resultados / suma
    return prob

def invertir_resultados(r):
  n = len(r)
  aux1 = np.sort(r)
  aux2 = np.sort(r)[::-1]
  resultados_invertidos = []
  for i in range(n):
      for j in range(n):
          if r[i] == aux1[j]:
              resultados_invertidos.append(aux2[j])
              j=n
  return resultados_invertidos

def probabilidad_seleccion_acumulada(prob_i,n):
  prob_i=np.array(prob_i)
  prob_sa = prob_i/(n*(n+1)*0.5)
  return prob_sa

# Given matrix
genotipos = np.array([[0, 0, 0, 1, 0, 1],
                         [0, 1, 1, 0, 1, 1],
                         [1, 1, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 1],
                         [1, 0, 0, 0, 0, 1],
                         [1, 1, 1, 1, 1, 1]])

fenotipos = binary_matrix_to_decimal_signed(genotipos)
resultados = f(fenotipos)
suma, minimo, media = calcular_estadisticas(resultados)
prob = probabilidad(resultados,suma)
prob_i = invertir_resultados(prob)
n=5
prob_sa = probabilidad_seleccion_acumulada(prob_i,n)

print(f"Genotipos:\n{genotipos}")
print(f"Fenotipos: {fenotipos}\n")
print("El resultado de f(x) para cada fenotipo es:")
for x, result in zip(fenotipos, resultados):
    print(f"{result}")



print(f"\nSuma total: {suma}")
print(f"Valor mínimo: {minimo}")
print(f"Media: {media}")

print(f"\nResultados divididos por la suma: {prob}")
np.sum(prob)

print(f"Resultados invertidos: {prob_i}")

print(f"Probabilidad de selccón acumulada: {prob_sa}")


a
Genotipos:
[[0 0 0 1 0 1]
 [0 1 1 0 1 1]
 [1 1 0 0 0 0]
 [0 1 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]
Fenotipos: [5, 27, -16, 17, -31, -1]

El resultado de f(x) para cada fenotipo es:
2226.197386538649
43095907488745.69
-5.401688386524437e-06
1231902590.4323401
-3.2015037108770783e-12
-1.103638323514327

Suma total: 43097139393561.21
Valor mínimo: -1.103638323514327
Media: 7182856565593.535

Resultados divididos por la suma: [ 5.16553400e-11  9.99971416e-01 -1.25337516e-19  2.85843239e-05
 -7.42857590e-26 -2.56081573e-14]
Resultados invertidos: [-7.428575900690496e-26, -2.5608157270856185e-14, 2.8584323873161487e-05, -1.2533751572688974e-19, 5.165533995676861e-11, 0.9999714156244972]
Probabilidad de selccón acumulada: [-4.95238393e-27 -1.70721048e-15  1.90562159e-06 -8.35583438e-21
  3.44368933e-12  6.66647610e-02]
