<a href="https://colab.research.google.com/github/anruki/APRENDIZAJE_AUTOMATICO_23_24/blob/main/AlgGen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math
def binary_matrix_to_decimal_signed(binary_matrix):
    """
    Converts a binary matrix to its signed decimal equivalents using two's complement.

    Parameters:
    - binary_matrix: 2D NumPy array or list of lists where each row represents a binary vector.

    Returns:
    - decimal_values: List of signed decimal equivalents for each binary vector.
    """
    binary_matrix = np.array(binary_matrix)
    num_vectors, vector_length = binary_matrix.shape

    decimal_values = []

    for vector_index in range(num_vectors):
        decimal_value = 0

        # Check if the binary vector is negative (MSB is 1)
        if binary_matrix[vector_index, 0] == 1:
            # Convert the binary vector to its signed decimal equivalent using two's complement
            binary_vector = binary_matrix[vector_index]
            inverted_vector = 1 - binary_vector
            decimal_value = -1 * (int(''.join(map(str, inverted_vector)), 2) + 1)
        else:
            # Convert the positive binary vector to decimal
            for bit_index in range(vector_length):
                decimal_value += binary_matrix[vector_index, bit_index] * (2 ** (vector_length - 1 - bit_index))

        decimal_values.append(decimal_value)

    return decimal_values

def calcular_estadisticas(resultados):
    """
    Calcula la suma, el mínimo y la media de un vector de resultados.

    Parámetros:
    - resultados: NumPy array o lista de resultados.

    Retorna:
    - suma_total: Suma de todos los resultados.
    - valor_minimo: Valor mínimo en el vector de resultados.
    - media: Media de los resultados.
    """
    resultados = np.array(resultados)
    suma_total = np.sum(resultados)
    valor_minimo = np.min(resultados)
    media = np.mean(resultados)

    return suma_total, valor_minimo, media



def f(x_vector):
    """
    Calculates the result of the expression 3 * x * exp(x) for each element in the input vector.

    Parameters:
    - x_vector: NumPy array or Python list of input values.

    Returns:
    - result_vector: NumPy array of results for each element in the input vector.
    """
    x_vector = np.array(x_vector)
    result_vector = 3 * x_vector * np.exp(x_vector)
    return result_vector

# Given matrix
genotipos = np.array([[0, 0, 0, 1, 0, 1],
                         [0, 1, 1, 0, 1, 1],
                         [1, 1, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 1],
                         [1, 0, 0, 0, 0, 1],
                         [1, 1, 1, 1, 1, 1]])

fenotipos = binary_matrix_to_decimal_signed(genotipos)
resultados = f(fenotipos)
suma, minimo, media = calcular_estadisticas(resultados)

print(f"Genotipos:\n{genotipos}")
print(f"Fenotipos: {fenotipos}\n")
print("El resultado de f(x) para cada fenotipo es:")
for x, result in zip(fenotipos, resultados):
    print(f"{result}")



print(f"Suma total: {suma}")
print(f"Valor mínimo: {minimo}")
print(f"Media: {media}")

Genotipos:
[[0 0 0 1 0 1]
 [0 1 1 0 1 1]
 [1 1 0 0 0 0]
 [0 1 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]
Fenotipos: [5, 27, -16, 17, -31, -1]

El resultado de f(x) para cada fenotipo es:
2226.197386538649
43095907488745.69
-5.401688386524437e-06
1231902590.4323401
-3.2015037108770783e-12
-1.103638323514327
Suma total: 43097139393561.21
Valor mínimo: -1.103638323514327
Media: 7182856565593.535
