<a href="https://colab.research.google.com/github/anruki/APRENDIZAJE_AUTOMATICO_23_24/blob/main/Copia_de_Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
import math
def binary_matrix_to_decimal_signed(binary_matrix):
    """
    Converts a binary matrix to its signed decimal equivalents using two's complement.

    Parameters:
    - binary_matrix: 2D NumPy array or list of lists where each row represents a binary vector.

    Returns:
    - decimal_values: List of signed decimal equivalents for each binary vector.
    """
    binary_matrix = np.array(binary_matrix)
    num_vectors, vector_length = binary_matrix.shape

    decimal_values = []

    for vector_index in range(num_vectors):
        decimal_value = 0

        # Check if the binary vector is negative (MSB is 1)
        if binary_matrix[vector_index, 0] == 1:
            # Convert the binary vector to its signed decimal equivalent using two's complement
            binary_vector = binary_matrix[vector_index]
            inverted_vector = 1 - binary_vector
            decimal_value = -1 * (int(''.join(map(str, inverted_vector)), 2) + 1)
        else:
            # Convert the positive binary vector to decimal
            for bit_index in range(vector_length):
                decimal_value += binary_matrix[vector_index, bit_index] * (2 ** (vector_length - 1 - bit_index))

        decimal_values.append(decimal_value)

    return decimal_values

def calcular_estadisticas(resultados):
    """
    Calcula la suma, el mínimo y la media de un vector de resultados.

    Parámetros:
    - resultados: NumPy array o lista de resultados.

    Retorna:
    - suma_total: Suma de todos los resultados.
    - valor_minimo: Valor mínimo en el vector de resultados.
    - media: Media de los resultados.
    """
    resultados = np.array(resultados)
    suma_total = np.sum(resultados)
    valor_minimo = np.min(resultados)
    media = np.mean(resultados)

    return suma_total, valor_minimo, media



def f(x_vector):
    """
    Calculates the result of the expression 3 * x * exp(x) for each element in the input vector.

    Parameters:
    - x_vector: NumPy array or Python list of input values.

    Returns:
    - result_vector: NumPy array of results for each element in the input vector.
    """
    x_vector = np.array(x_vector)
    result_vector = 3 * x_vector * np.exp(x_vector)
    return result_vector

def probabilidad(resultados,suma):
    resultados = np.array(resultados)
    prob = resultados / suma
    return prob

def invertir_resultados(r):
  n = len(r)
  aux1 = np.sort(r)
  aux2 = np.sort(r)[::-1]
  resultados_invertidos = []
  for i in range(n):
      for j in range(n):
          if r[i] == aux1[j]:
              resultados_invertidos.append(aux2[j])
              j=n
  print("a")
  return resultados_invertidos



# Given matrix
genotipos = np.array([[0, 0, 0, 1, 0, 1],
                         [0, 1, 1, 0, 1, 1],
                         [1, 1, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 1],
                         [1, 0, 0, 0, 0, 1],
                         [1, 1, 1, 1, 1, 1]])

fenotipos = binary_matrix_to_decimal_signed(genotipos)
resultados = f(fenotipos)
suma, minimo, media = calcular_estadisticas(resultados)
prob = probabilidad(resultados,suma)
prob_i = invertir_resultados(prob)

print(f"Genotipos:\n{genotipos}")
print(f"Fenotipos: {fenotipos}\n")
print("El resultado de f(x) para cada fenotipo es:")
for x, result in zip(fenotipos, resultados):
    print(f"{result}")



print(f"\nSuma total: {suma}")
print(f"Valor mínimo: {minimo}")
print(f"Media: {media}")

print(f"\nResultados divididos por la suma: {prob}")
np.sum(prob)

resultados_invertidos = invertir_resultados(prob)
print(f"Resultados invertidos: {resultados_invertidos}")

a
Genotipos:
[[0 0 0 1 0 1]
 [0 1 1 0 1 1]
 [1 1 0 0 0 0]
 [0 1 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]
Fenotipos: [5, 27, -16, 17, -31, -1]

El resultado de f(x) para cada fenotipo es:
2226.197386538649
43095907488745.69
-5.401688386524437e-06
1231902590.4323401
-3.2015037108770783e-12
-1.103638323514327

Suma total: 43097139393561.21
Valor mínimo: -1.103638323514327
Media: 7182856565593.535

Resultados divididos por la suma: [ 5.16553400e-11  9.99971416e-01 -1.25337516e-19  2.85843239e-05
 -7.42857590e-26 -2.56081573e-14]
a
Resultados invertidos: [-7.428575900690496e-26, -2.5608157270856185e-14, 2.8584323873161487e-05, -1.2533751572688974e-19, 5.165533995676861e-11, 0.9999714156244972]


In [34]:
import numpy as np

# Función de aptitud (fitness)
def fitness(individuo):
    return np.sum(individuo)

# Función de inicialización de la población
def inicializar_poblacion(tamano_poblacion, longitud_individuo):
    return np.random.randint(2, size=(tamano_poblacion, longitud_individuo))

# Operador de selección (ruleta)
def seleccion(poblacion, puntuaciones):
    probabilidades = puntuaciones / puntuaciones.sum()
    indices_seleccionados = np.random.choice(len(poblacion), size=len(poblacion), p=probabilidades)
    return poblacion[indices_seleccionados]

# Operador de cruce (crossover)
def cruce(padre1, padre2):
    padre1 = np.array(padre1)
    padre2 = np.array(padre2)

    punto_cruce = np.random.randint(1, len(padre1) - 1)
    hijo1 = np.concatenate((padre1[:punto_cruce], padre2[punto_cruce:]))
    hijo2 = np.concatenate((padre2[:punto_cruce], padre1[punto_cruce:]))
    return hijo1, hijo2

# Operador de mutación
def mutacion(individuo, tasa_mutacion):
    for i in range(len(individuo)):
        if np.random.rand() < tasa_mutacion:
            individuo[i] = 1 - individuo[i]
    return individuo

# Algoritmo genético
def algoritmo_genetico(tamano_poblacion, longitud_individuo, generaciones, tasa_mutacion):
    poblacion = inicializar_poblacion(tamano_poblacion, longitud_individuo)

    for generacion in range(generaciones):
        puntuaciones = np.array([fitness(individuo) for individuo in poblacion])
        poblacion_seleccionada = seleccion(poblacion, puntuaciones)

        nueva_poblacion = []
        for _ in range(tamano_poblacion // 2):
            padre1, padre2 = np.random.choice(poblacion_seleccionada.flatten(), size=2, replace=False)
            hijo1, hijo2 = cruce(padre1, padre2)
            hijo1 = mutacion(hijo1, tasa_mutacion)
            hijo2 = mutacion(hijo2, tasa_mutacion)
            nueva_poblacion.extend([hijo1, hijo2])

        poblacion = np.array(nueva_poblacion)

    mejor_individuo = poblacion[np.argmax(puntuaciones)]
    mejor_aptitud = np.max(puntuaciones)

    return mejor_individuo, mejor_aptitud

# Ejemplo de uso
tamano_poblacion = 50
longitud_individuo = 10
generaciones = 100
tasa_mutacion = 0.1

mejor_individuo, mejor_aptitud = algoritmo_genetico(tamano_poblacion, longitud_individuo, generaciones, tasa_mutacion)

print("Mejor individuo:", mejor_individuo)
print("Mejor aptitud:", mejor_aptitud)

TypeError: ignored